### ISSUE TITLE
[Question] How to load a particular MIB File

### ISSUE THREAD

**Issue by aldevar** [cavaliercoder/mib2zabbix#1]
Hi, 

I'm trying to use your script to generate a template from the BGP4-MIB file.
I'm looking for an option to just load this file.

The actual behavior is that the script loads all MIB files present in /usr/share/snmp/mibs/ and generate a 52000 lines template with all MIBS.

Thanks for your work.
Regards,

**Comment by cavaliercoder** [comment]
Thanks for posting your question. mib2zabbix relies on the NetSNMP library to traverse MIB files. NetSNMP requires that MIB files be loaded from the directory you described, or `$HOME/.snmp/mibs`. Please see the [NetSNMP documentation](http://net-snmp.sourceforge.net/tutorial/tutorial-5/commands/mib-options.html) for more information on loading MIB files.

Once the MIB file is loaded into the MIB tree, you can select the OID which you wish to generate a Zabbix template for, by specifying the `-o` flag when you call mib2zabbix. MIB files typically contain multiple root OIDs, so it's worth inspecting the file to decide which part of the tree you wish to generate a template for. If no OID is given, the entire tree is exported to a template, as you have experienced.

**Comment by aldevar** [comment]
Ok, I see that I misunderstodd the use of mib2zabbix at the first time.
Thank you for your answer

**Comment by cavaliercoder** [comment]
I'm glad you asked, thank you. This may help others too. I need to put together a tutorial soon!

**Comment by Gmatoy** [comment]
i need one, i am tottaly lost on this!
