### ISSUE TITLE
guide to implement

### ISSUE THREAD

**Issue by jashankochar** [cavaliercoder/mib2zabbix#12]
someone please guide steps to implement it

**Comment by jashankochar** [comment]
-bash: mib2zabbix.pl: command not found

**Comment by cavaliercoder** [comment]
You need to put the script into one of your `$PATH` directories or invoke it using a full path.
E.g. `$ ./mib2zabbix.pl`. This is fairly standard practice in unix/linux.

I am working on a more detailed guide blog entry, but this won't be available for some time.

**Comment by jashankochar** [comment]
where that template will be saved after running

**Comment by cavaliercoder** [comment]
It prints to stdout. You need to pipe it to a file.
