### ISSUE TITLE
Template does not contain all parts of mib

### ISSUE THREAD

**Issue by starlessboi** [cavaliercoder/mib2zabbix#23]
Hi all
I'm trying to convert mib file:
https://userweb.jlab.org/~brads/Manuals/Hardware/Liebert-Emerson_GXT_UPS/SNMP_MIBs/Upsmate.mib
to zabbix template
it has root oid: .1.3.6.1.4.1.935
it seems to be converted (without error), but not all parts are in template after import
can you help me, what could be problem?
also does your script supports zabbix version 4?
thanks

**Comment by cavaliercoder** [comment]
Sometimes there are MIB data types that aren't supported by Zabbix, or impossible to map programmatically, so they just get skipped. These should be printed to stderr by the script.

Zabbix v4 should work fine, though I haven't explicitly updated the script to take advantage of v4 features.

**Comment by starlessboi** [comment]
Hi
Thanks for your answer, That was my fault, I Finally did it, and converted to Zabbix template successfully.
Also it imported and used in Zabbix version 4.0.3 without problem.
thanks again

**Comment by cavaliercoder** [comment]
Thanks for the update. Happy monitoring!
