### ISSUE TITLE
Version 5

### ISSUE THREAD

**Issue by colin-small** [cavaliercoder/mib2zabbix#26]
Will this work with version 5 of Zabbix or does it need to be updated? If it does need to be updated, do you plan up doing that?

**Comment by isaqueprofeta** [comment]
AFAIK XML structure of Zabbix hasn't changed between v3 till now on v5, so yeah it's still WAI.

@cavaliercoder I think you can close this.

**Comment by cavaliercoder** [comment]
Thanks @isaqueprofeta. I no longer work with Zabbix and have not tested on v5. I won't be maintaining this script anymore, sorry.
