### ISSUE TITLE
Low Level Discovery OID Error

### ISSUE THREAD

**Issue by akayueh** [cavaliercoder/mib2zabbix#4]
Hi Ryan

There seems to be an error in your Low-Level SNMP OID.

For example in the Doremi Template:

**From Template:**

Name:  dcpSENfansEntry Discovery
Key:  DOREMI-DC-DCPLAYER-MIB.dcpSENfansEntry
SNMP OID:  discovery[{#DCPFANHIGHTHRESHOLD},.1.3.6.1.4.1.24391.4.1.3.3.1.1.1.6,{#DCPFANLOWTHRESHOLD},.1.3.6.1.4.1.24391.4.1.3.3.1.1.1.5,{#DCPFANVALUE},.1.3.6.1.4.1.24391.4.1.3.3.1.1.1.4,{#DCPFANWORKINGSTATE},.1.3.6.1.4.1.24391.4.1.3.3.1.1.1.3]

**FromMIB Browser Software (e.g. iReasoning MIB Brower):**
Name:  dcpSENfansEntry
Key:  DOREMI-DC-DCPLAYER-MIB.dcpSENfansEntry
OID:  .1.3.6.1.4.1.24391.4.1.3.3.1.1.1
OID Full Name:  .iso.org.dod.internet.private.enterprises.doremiHQRoot.drmDCRoot.drmdcDCPlayerMib.dcpModulesRoot.dcpSensors.dcpSENprobes.dcpSENfansTable.dcpSENfansEntry

**Comment by akayueh** [comment]
[Doremi OID From iReasoning.zip](https://github.com/cavaliercoder/mib2zabbix/files/424280/Doremi.OID.From.iReasoning.zip)

**Comment by akayueh** [comment]
bummer, I see the syntax is for the new v3....  More work for me then....

**Comment by cavaliercoder** [comment]
The initial commit only supported Zabbix v2 (https://github.com/cavaliercoder/mib2zabbix/blob/7d293da3fc2e1f8354871b4be52a2c3fa686bb69/mib2zabbix.pl).

I've since updated the script to only support v3, but I'm hopeful you will submit a PR to support v2 and v3 in parallel in #3 :)
